services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: podomed
    ports:
      - "5432:5432"
    volumes:
      - podomed_pg:/var/lib/postgresql/data

volumes:
  podomed_pg:
